Repository KeplerStation/KeplerStation, pull requests merged in 2019-06, with the labels that each got.

#1 Initial kepler-ifying
  .github/CODEOWNERS
  README.md
  kepler/tools/merge-upstream-pull-request.sh
  modular_kepler/README.md
Labels: Documentation, High Priority, Tooling

#2 Tweaks to the script
  kepler/tools/merge-upstream-pull-request.sh
Labels: Administration, Code Improvement/Refactor, FUCK, High Priority, Tooling

#9 Removes lewdness from the maps
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: FUCK, High Priority, Map Edit, Needs Review, Removal

#17 Adds BSQL and Rust-G to TGS3
  TGS3.json
Labels: Blame Affected, FUCK, Fix, High Priority, Tooling

#36 The real TGS3 Fix
  TGS3.json
Labels: Blame Affected, FUCK, Fix, High Priority

#38 no
  code/controllers/subsystem/processing/circuit.dm
  code/modules/integrated_electronics/core/assemblies.dm
  icons/obj/assemblies/electronic_setups.dmi
  icons/obj/citvending.dmi
  modular_citadel/code/modules/antagonists/crew_objectives/cit_crewobjectives_civilian.dm
Labels: FUCK, High Priority

#39 commands
  code/game/objects/effects/overlays.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/mob_defines.dm
  icons/effects/effects.dmi
Labels: Administration, Feature, Sprites, Tweak

#40 Re-adds Strawberry milk/tea
  code/modules/food_and_drinks/recipes/drinks_recipes.dm
Labels: Feature

#66 DMAPI
  code/__DEFINES/tgs.config.dm
  code/__DEFINES/tgs.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/core/default_event_handler.dm
  code/modules/tgs/core/tgs_version.dm
  code/modules/tgs/includes.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v4/commands.dm
  tools/mapmerge2/mapmerge.bat
Labels: Blame Affected, FUCK, High Priority, Stale, Tooling, Tweak

#68 Fixes species stuff
  code/datums/dna.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: FUCK, Fix

#70 SSChat_prompt
  code/controllers/subsystem/chat_prompts.dm
  config/idle_announce.txt
  tgstation.dme
Labels: Config Update, Feature

#69 Removes mice wire eating
  code/modules/mob/living/simple_animal/friendly/mouse.dm
Labels: Code Improvement/Refactor, Removal, Tweak

#72 Revert "Removes roundstart game vote"
  code/controllers/subsystem/vote.dm
Labels: Removal, Revert

#71 Removes roundstart game vote
  code/controllers/subsystem/vote.dm
Labels: Removal

#75 Fixes mapmerge python path
  tools/mapmerge2/mapmerge.bat
Labels: Blame Affected, FUCK, Fix, Tools

#73 Changes our taskbar icon
  icons/kepler_64.png
  modular_citadel/interface/skin.dmf
Labels: Sprites, Tweak

#78 roundstart vote as config
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  config/game_options.txt
Labels: Config Update, Tweak

#113 Fix undeleted queries
  modular_citadel/code/modules/mentor/mentor.dm
  modular_citadel/code/modules/mentor/mentor_memo.dm
Labels: Fix, Tweak

#114 Crispy Status Displays
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/status_display.dm
Labels: Tweak

#115 Makes "me" a small box
  code/modules/mob/say.dm
Labels: Tweak

#117 Affecteds Big Fat PDA Redesign
  code/__DEFINES/misc.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/virus_cart.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  html/browser/common.css
  icons/pda_icons/pda_atmos.png
  icons/pda_icons/pda_back.png
  icons/pda_icons/pda_bell.png
  icons/pda_icons/pda_blank.png
  icons/pda_icons/pda_boom.png
  icons/pda_icons/pda_bucket.png
  icons/pda_icons/pda_chatroom.png
  icons/pda_icons/pda_cleanbot.png
  icons/pda_icons/pda_color.png
  icons/pda_icons/pda_crate.png
  icons/pda_icons/pda_cuffs.png
  icons/pda_icons/pda_dronephone.png
  icons/pda_icons/pda_eject.png
  icons/pda_icons/pda_exit.png
  icons/pda_icons/pda_flashlight.png
  icons/pda_icons/pda_floorbot.png
  icons/pda_icons/pda_font.png
  icons/pda_icons/pda_honk.png
  icons/pda_icons/pda_locked.PNG
  icons/pda_icons/pda_mail.png
  icons/pda_icons/pda_medbot.png
  icons/pda_icons/pda_medical.png
  icons/pda_icons/pda_menu.png
  icons/pda_icons/pda_mule.png
  icons/pda_icons/pda_notes.png
  icons/pda_icons/pda_power.png
  icons/pda_icons/pda_rdoor.png
  icons/pda_icons/pda_reagent.png
  icons/pda_icons/pda_refresh.png
  icons/pda_icons/pda_scanner.png
  icons/pda_icons/pda_signaler.png
  icons/pda_icons/pda_status.png
Labels: Sprites, Tweak

#143 Freeze admin log
  code/modules/admin/verbs/randomverbs.dm
Labels: Feature

#142 Give verb
  code/modules/mob/living/carbon/give.dm
  tgstation.dme
Labels: Fix, LIKE COMMENT AND SUBSCRIBE

#132 [REVIEW READY] Removes epithets/major fourth wall breaks/etc.
  _maps/RandomRuins/SpaceRuins/bus.dmm
  code/game/objects/items/manuals.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/food_and_drinks/food/snacks_meat.dm
  code/modules/food_and_drinks/recipes/processor_recipes.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_meat.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pastry.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_pizza.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_salad.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_soup.dm
  code/modules/food_and_drinks/recipes/tablecraft/recipes_spaghetti.dm
  code/modules/holiday/easter.dm
  config/mentors.txt
  html/archivedchangelog.html
  icons/obj/food/food.dmi
  strings/insult.json
  strings/ion_laws.json
  strings/names/death_commando.txt
  strings/traumas.json
Labels: Config Update, Map Edit, Removal, Sprites, Tweak

#154 Fixes JSON files
  strings/canadian_replacement.json
  strings/french_replacement.json
  strings/insult.json
  strings/ion_laws.json
  strings/italian_replacement.json
  strings/pirates.json
  strings/revenant_names.json
  strings/traumas.json
Labels: Fix

#155 Update death_commando.txt
  strings/names/death_commando.txt
Labels: Feature, Removal
