Repository KeplerStation/KeplerStation, pull requests merged in 2019-09, with the labels that each got.

#552 Tweaks Radiation Storms
  code/datums/weather/weather_types/radiation_storm.dm
  code/modules/events/_event.dm
  code/modules/events/radiation_storm.dm
Labels: Fix, Tweak

#554 Makes all autodrobes all access
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
Labels: Fix, Map Edit, Tweak

#567 Fixes windoors
  code/_onclick/adjacent.dm
Labels: Fix

#553 Antag Picking Tweaks
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/game_mode.dm
Labels: Fix, Tweak

#595 Who verb mentor color
  modular_citadel/code/modules/client/verbs/who.dm
Labels: Tweak

#596 Mentor OOC color.
  code/__DEFINES/kepler_defines.dm
  code/modules/client/verbs/ooc.dm
  tgstation.dme
Labels: Feature

#610 AI Laws
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/datums/ai_laws.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/AI_modules.dm
  code/modules/research/designs/AI_module_designs.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature, Map Edit, Removal, Tweak

#609 Crewsimov
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  _maps/map_files/OmegaStation/OmegaStation.dmm
  _maps/map_files/PubbyStation/PubbyStation.dmm
  code/datums/ai_laws.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/game/objects/items/AI_modules.dm
  code/modules/research/designs/AI_module_designs.dm
  code/modules/research/techweb/all_nodes.dm
  config/example/game_options.txt
  config/example/silicon_laws.txt
Labels: Blame Affected, Config Update, Feature, Map Edit, Tweak

#613 Removes Subtler
  code/modules/mob/say_vr.dm
Labels: Removal

#614 Renames pockets
  code/_onclick/hud/human.dm
Labels: Grammar and Formatting

#611 Tweaks new account join message for admins
  code/modules/client/client_procs.dm
Labels: Administration

#646 PDA Slots
  code/__DEFINES/inventory.dm
  code/__DEFINES/kepler_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/outfit.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/pinpointer.dm
  code/modules/awaymissions/corpse.dm
  code/modules/clothing/outfits/standard.dm
  code/modules/jobs/access.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/civilian_chaplain.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/job.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/mob/update_icons.dm
  modular_kepler/icons/mob/screen_clockwork.dmi
  modular_kepler/icons/mob/screen_midnight.dmi
  modular_kepler/icons/mob/screen_operative.dmi
  modular_kepler/icons/mob/screen_plasmafire.dmi
  modular_kepler/icons/mob/screen_retro.dmi
  modular_kepler/icons/mob/screen_slimecore.dmi
Labels: Feature

#674 Start round confirmation
  code/modules/admin/admin.dm
Labels: Feature
