Repository KeplerStation/KeplerStation, pull requests merged in 2019-10, with the labels that each got.

#676 custom emote in say tweak
  modular_citadel/code/modules/mob/mob.dm
Labels: Fix

#683 quirk blood checking
  code/datums/traits/_quirk.dm
  code/datums/traits/negative.dm
  code/modules/client/preferences.dm
Labels: Fix

#691 Mentohelp Noise change
  modular_citadel/code/modules/mentor/mentorhelp.dm
  modular_citadel/code/modules/mentor/mentorpm.dm
Labels: Tweak

#755 Undoes fractioning of reactions.
  code/modules/reagents/chemistry/holder.dm
Labels: Fix

#759 Fixes job code
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/bartender.dm
  code/modules/jobs/job_types/botanist.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/cargo_technician.dm
  code/modules/jobs/job_types/chaplain.dm
  code/modules/jobs/job_types/chemist.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/chief_medical_officer.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/clown.dm
  code/modules/jobs/job_types/cook.dm
  code/modules/jobs/job_types/curator.dm
  code/modules/jobs/job_types/detective.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/geneticist.dm
  code/modules/jobs/job_types/head_of_personnel.dm
  code/modules/jobs/job_types/head_of_security.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/jobs/job_types/lawyer.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/medical_doctor.dm
  code/modules/jobs/job_types/mime.dm
  code/modules/jobs/job_types/quartermaster.dm
  code/modules/jobs/job_types/research_director.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/scientist.dm
  code/modules/jobs/job_types/security.dm
  code/modules/jobs/job_types/security_officer.dm
  code/modules/jobs/job_types/shaft_miner.dm
  code/modules/jobs/job_types/station_engineer.dm
  code/modules/jobs/job_types/virologist.dm
  code/modules/jobs/job_types/warden.dm
Labels: Fix

#771 Fix head of staff cryo message
  code/game/machinery/cryopod.dm
Labels: Fix

#770 medicalf and cmof cross recolor
  icons/obj/clothing/uniforms.dmi
Labels: Fix, Sprites

#772 Fixes digi suits
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#797 Hotfix for latejoin Omega jobs
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#816 Revert omega job snowflake
  code/modules/mob/dead/new_player/new_player.dm
Labels: Code Improvement, Revert

#817 Check for input in custom emotes
  modular_citadel/code/modules/mob/mob.dm
Labels: Fix

#823 Fix pda_slot runtime
  code/modules/jobs/job_types/atmospheric_technician.dm
  code/modules/jobs/job_types/chief_engineer.dm
  code/modules/jobs/job_types/roboticist.dm
  code/modules/jobs/job_types/station_engineer.dm
Labels: Fix

#824 Properly imports plasmaman suit icons
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  tgstation.dme
Labels: Fix, Sprites

#825 Plasmaman tongue runtime fix
  code/modules/surgery/organs/organ_internal.dm
  code/modules/surgery/organs/tongue.dm
Labels: Fix

#826 Fixes non-silicons being able to beep
  code/modules/mob/emote.dm
Labels: Fix

#844 Tweaks to Meta and Box cargo
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
Labels: Feature, Map Edit

#843 Ports over missing icons
  icons/obj/surgery.dmi
Labels: Fix, Sprites

#845 Fixes TGS version reporting
  code/datums/helper_datums/getrev.dm
Labels: Fix

#858 Fixes widescreen for now
  code/modules/tooltip/tooltip.html
Labels: Fix

#882 Makes round time offset
  code/modules/mob/mob.dm
Labels: Tweak

#810 [READY] 513 Compile
  Dockerfile
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/unsorted.dm
  code/datums/components/phantomthief.dm
Labels: FUCK, Needs Review, Tweak
