Repository KeplerStation/KeplerStation, pull requests merged in 2019-08, with the labels that each got.

#359 shuttle changes
  code/modules/shuttle/emergency.dm
Labels: Tweak

#362 Chat color
  code/modules/goonchat/browserassets/css/browserOutput.css
Labels: Fix

#364 [Omega] Map fixes
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit, Tweak

#378 Fixes a map edit that shouldnt have happened
  _maps/map_files/Deltastation/DeltaStation2.dmm
Labels: Map Edit

#360 [Take 50] Makes parsing work
  code/controllers/subsystem/server_maint.dm
  code/game/world.dm
Labels: Administration, Blame Affected, Fix, Tools

#380 Fixes TOS runtime
  modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
Labels: Fix

#385 Fixes emotes for the billionth time
  code/modules/mob/emote.dm
Labels: Fix

#383 Tweaks to Adminwho and Who
  modular_citadel/code/modules/client/verbs/who.dm
Labels: Tweak

#421 Makes combat mode mouse looking work again
  code/game/atoms.dm
  modular_citadel/code/_onclick/click.dm
Labels: Fix

#377 Travis Update
  .editorconfig
  .travis.yml
  dependencies.sh
  tools/json_verifier.py
  tools/travis/before_build_tools.sh
  tools/travis/build_bsql.sh
  tools/travis/build_byond.sh
  tools/travis/build_dependencies.sh
  tools/travis/build_tgui.sh
  tools/travis/build_tools.sh
  tools/travis/check_changelogs.sh
  tools/travis/check_grep.sh
  tools/travis/install_build_tools.sh
  tools/travis/install_byond.sh
  tools/travis/install_dreamchecker.sh
  tools/travis/install_libmariadb.sh
  tools/travis/install_rust_g.sh
  tools/travis/run_server.sh
Labels: Code Improvement, Tools

#423 Dreamchecker fail hotfix
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
Labels: Code Improvement

#414 Parser, Take 3
  SQL/kepler_schema.sql
  SQL/tos.sql
  code/__HELPERS/_logging.dm
  code/controllers/subsystem/server_maint.dm
  config/config.txt
  modular_kepler/code/controllers/configuration/entries/general.dm
  tgstation.dme
Labels: Config Update, FUCK, Fix, SQL

#420 Makes megafauna gib
  code/modules/mob/living/simple_animal/hostile/megafauna/colossus.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/hierophant.dm
  code/modules/mob/living/simple_animal/hostile/megafauna/megafauna.dm
Labels: Fix

#424 Fixes TOS again
  modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
Labels: Fix

#456 Fixes Stockings
  icons/mob/underwear.dmi
Labels: Fix, Sprites

#482 Fixes some mistakes in the techweb
  code/modules/research/techweb/all_nodes.dm
Labels: Fix

#479 Linux Support
  .travis.yml
  code/__DEFINES/rust_g.dm
  code/modules/bsql/core/library.dm
  libBSQL.so
  libmariadb.so
  librust_g.so
  tools/travis/build_bsql.sh
  tools/travis/install_libs.sh
  tools/travis/install_rust_g.sh
Labels: Tools

#496 Genders and nameless
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/job.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
Labels: Fix, Removal

#493 Updates changelog to our codebase
  html/templates/header.html
Labels: Tweak

#501 [Omega] Xenobio Tweaks
  _maps/map_files/OmegaStation/OmegaStation.dmm
Labels: Fix, Map Edit

#499 Update TGUI Dependencies
  tgui/assets/tgui.css
  tgui/assets/tgui.js
  tgui/gulp/css.js
  tgui/gulp/plugins.js
  tgui/package-lock.json
  tgui/package.json
Labels: Code Improvement, UI

#358 Slime changes
  code/__DEFINES/DNA.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  icons/mob/human_parts_greyscale.dmi
  modular_citadel/code/modules/mob/living/carbon/human/species_types/jellypeople.dm
Labels: Do Not Merge, Feature, Sprites, Tweak

#509 Fixes dependencies (Again)
  tgui/assets/tgui.js
  tgui/package-lock.json
  tgui/package.json
Labels: Fix, UI

#510 Fixes wallets
  code/game/objects/items/storage/wallets.dm
Labels: Fix

#511 Fixes holopads for AIs
  code/modules/mob/living/silicon/ai/say.dm
  modular_citadel/code/modules/mob/mob.dm
Labels: Fix

#514 Oracle UI
  code/controllers/subsystem/assets.dm
  code/modules/paperwork/paper.dm
  code/modules/recycling/disposal/bin.dm
  modular_kepler/code/modules/oracle_ui/README.md
  modular_kepler/code/modules/oracle_ui/assets.dm
  modular_kepler/code/modules/oracle_ui/hookup_procs.dm
  modular_kepler/code/modules/oracle_ui/oracle_ui.dm
  modular_kepler/code/modules/oracle_ui/themed.dm
  modular_kepler/html/oracle_ui/content/disposal_bin/index.html
  modular_kepler/html/oracle_ui/editor_tool.html
  modular_kepler/html/oracle_ui/themes/nano/index.html
  modular_kepler/html/oracle_ui/themes/nano/sui-nano-common.css
  modular_kepler/html/oracle_ui/themes/nano/sui-nano-common.js
  modular_kepler/html/oracle_ui/themes/nano/sui-nano-jquery.min.js
  tgstation.dme
Labels: Feature, Refactor
