Repository KeplerStation/KeplerStation, pull requests merged in 2019-11, with the labels that each got.

#918 Ports research unmodularization from upstream
  code/modules/research/designs/electronics_designs.dm
  code/modules/research/designs/machine_desings/machine_designs_all_misc.dm
  code/modules/research/designs/weapon_designs.dm
  code/modules/research/techweb/_techweb.dm
  code/modules/research/xenobiology/xenobio_camera.dm
  modular_citadel/code/modules/research/designs/machine_designs.dm
  modular_citadel/code/modules/research/designs/weapon_designs.dm
  modular_citadel/code/modules/research/designs/weapon_designs/weapon_designs.dm
  modular_citadel/code/modules/research/designs/xenobio_designs.dm
  modular_citadel/code/modules/research/techweb/_techweb.dm
  modular_citadel/code/modules/research/xenobiology/xenobio_camera.dm
  tgstation.dme
Labels: Code Improvement

#919 Manual port of upstream wizard fix pr
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/human/damage_procs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/silicon/damage_procs.dm
  code/modules/mob/living/silicon/pai/pai_defense.dm
  code/modules/mob/living/simple_animal/damage_procs.dm
  code/modules/spells/spell_types/shapeshift.dm
Labels: Fix, Tweak

#922 New Blood Red Hardsuits
  code/modules/clothing/spacesuits/hardsuit.dm
  modular_kepler/icons/mob/head.dmi
  modular_kepler/icons/mob/suit.dmi
  modular_kepler/icons/obj/clothing/hats.dmi
  modular_kepler/icons/obj/clothing/suits.dmi
Labels: Sprites

#913 Adds ancient toolbox
  code/game/objects/items/storage/toolbox.dm
  code/modules/uplink/uplink_items.dm
  modular_kepler/icons/obj/storage/oldtoolboxclean.dmi
Labels: Feature, Sprites

#958 Removes some left over citadel files
  modular_citadel/code/modules/reagents/chemistry/reagents/MKUltra.dm
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/markings_notmammals.dmi
Labels: Removal

#959 Hardsuit helmets are spaceproof again
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#960 Genpop on Box!
  _maps/map_files/BoxStation/BoxStation.dmm
  code/game/machinery/turnstile.dm
Labels: Feature, Map Edit

#982 Fixes temperature alerts
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#979 Adds a verb to force recreate the chat object
  modular_kepler/code/modules/client/verbs/ooc.dm
  tgstation.dme
Labels: Feature

#990 Tweaks our gitignore file
  .gitignore
Labels: Tweak

#992 Modularises PDA painter icon
  code/game/machinery/PDApainter.dm
  icons/obj/pda.dmi
  modular_kepler/icons/obj/pda.dmi
Labels: Fix, Sprites, Tweak

#994 Fixes turnstile timing issues
  code/game/machinery/turnstile.dm
Labels: Fix

#995 Fixes sprites on cydonian armour
  code/modules/clothing/spacesuits/hardsuit.dm
Labels: Fix

#1031 Fixes emote spam
  code/datums/emotes.dm
  modular_citadel/code/modules/mob/cit_emotes.dm
Labels: Fix

#1032 Significantly reduce supply point generation
  code/controllers/subsystem/shuttle.dm
Labels: Fix

#991 Force loads a VR level
  code/controllers/subsystem/mapping.dm
  modular_kepler/code/controllers/subsystem/mapping.dm
  modular_kepler/code/modules/vr/vr_levels.dm
  tgstation.dme
Labels: Feature

#993 Removes joy mask
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/vending/autodrobe.dm
Labels: Removal

#1073 Nanite defines
  code/__DEFINES/nanites.dm
  code/modules/research/nanites/nanite_programs/sensor.dm
  code/modules/research/nanites/nanite_programs/suppression.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/nanites/nanite_programs/weapon.dm
Labels: Code Improvement

#1074 Manual upstream porting
  _maps/RandomZLevels/TheBeach.dmm
  _maps/RandomZLevels/beach.dmm
  _maps/RandomZLevels/beach2.dmm
  _maps/map_files/BoxStation/BoxStation.dmm
  _maps/map_files/Deltastation/DeltaStation2.dmm
  _maps/map_files/MetaStation/MetaStation.dmm
  code/datums/wires/airlock.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/objects/effects/decals/turfdecal/weather.dm
  code/game/objects/items/toys.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/fluff.dm
  code/game/turfs/space/space.dm
  code/modules/antagonists/cult/cult_items.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/cargo/exports/seeds.dm
  code/modules/events/anomaly_bluespace.dm
  code/modules/events/anomaly_flux.dm
  code/modules/events/anomaly_grav.dm
  code/modules/events/anomaly_pyro.dm
  code/modules/events/anomaly_vortex.dm
  code/modules/events/blob.dm
  code/modules/events/brand_intelligence.dm
  code/modules/events/carp_migration.dm
  code/modules/events/electrical_storm.dm
  code/modules/events/major_dust.dm
  code/modules/events/mice_migration.dm
  code/modules/events/prison_break.dm
  code/modules/events/shuttle_loan.dm
  code/modules/jobs/job_types/janitor.dm
  code/modules/keybindings/bindings_carbon.dm
  code/modules/keybindings/bindings_human.dm
  code/modules/keybindings/bindings_robot.dm
  code/modules/mining/mine_items.dm
  code/modules/modular_computers/hardware/network_card.dm
  code/modules/vending/_vending.dm
  config/example/awaymissionconfig.txt
  icons/effects/32x96.dmi
  icons/misc/beach.dmi
  icons/obj/fluff.dmi
  icons/turf/areas.dmi
  icons/turf/decals.dmi
  icons/turf/floors/dirt.dmi
  modular_citadel/code/datums/traits/negative.dm
  modular_citadel/code/datums/wires/airlock.dm
  modular_citadel/code/game/area/areas.dmi
  modular_citadel/code/game/area/cit_areas.dm
  modular_citadel/code/game/machinery/doors/airlock.dm
  modular_citadel/code/game/machinery/doors/airlock_types.dm
  modular_citadel/code/modules/keybindings/bindings_carbon.dm
  modular_citadel/code/modules/keybindings/bindings_human.dm
  modular_citadel/code/modules/keybindings/bindings_robot.dm
  tgstation.dme
Labels: Code Improvement, Config Update, Feature, Fix, Map Edit, Removal, Sprites

#1079 Adds myself as a code owner for config files
  .github/CODEOWNERS
Labels: GitHub

#1137 update sprites to upstream
  icons/obj/storage.dmi
Labels: Fix, Sprites

#1129 "fixing stupid pink milk and tea missing sprites."
  icons/obj/drinks.dmi
  modular_citadel/icons/obj/drinks.dmi
  tgstation.dme
Labels: Fix, Sprites

#1128 Adds research-boosting programs for nanites
  code/__DEFINES/nanites.dm
  code/controllers/subsystem/processing/nanites.dm
  code/modules/research/designs/nanite_designs.dm
  code/modules/research/nanites/nanite_programs/utility.dm
  code/modules/research/techweb/all_nodes.dm
Labels: Feature

#1130 More Dreamchecker Crap
  code/game/machinery/washing_machine.dm
  code/modules/clothing/gloves/_gloves.dm
  code/modules/clothing/shoes/_shoes.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
Labels: Tweak

#1168 Fixes glove washing infinite proc
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#1140 Fixes bones not being unbroken on admin rejuv
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/surgery/bodyparts/dismemberment.dm
Labels: Fix

#1187 Manual port of #1178
  code/modules/clothing/glasses/phantomthief.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  modular_citadel/code/modules/clothing/head/head.dm
  modular_citadel/code/modules/clothing/suits/suits.dm
  modular_citadel/icons/mob/clothing/space_nam.dmi
  modular_citadel/icons/obj/clothing/space_nam.dmi
  tgstation.dme
Labels: Code Improvement, Sprites

#1177 Adds moth markings
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/create_mob.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  icons/mob/moth_markings.dmi
  modular_kepler/code/modules/mob/dead/new_player/sprite_accessories/moth_markings.dm
  tgstation.dme
Labels: Feature, Sprites
