Repository KeplerStation/KeplerStation, pull requests merged in 2019-07, with the labels that each got.

#159 The Great Emote Migration
  code/game/objects/items/plushes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/brain/emote.dm
  code/modules/mob/living/carbon/alien/emote.dm
  code/modules/mob/living/carbon/alien/larva/emote.dm
  code/modules/mob/living/carbon/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_animal/hostile/gorilla/emotes.dm
  code/modules/mob/living/simple_animal/slime/emote.dm
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/sound/voice/awoo.ogg
  modular_citadel/sound/voice/merp.ogg
  modular_citadel/sound/voice/nya.ogg
  modular_citadel/sound/voice/weh.ogg
  tgstation.dme
Labels: Removal, Sound, Tweak

#158 [PORT] Reskinnable PDA's
  code/__DEFINES/misc.dm
  code/game/machinery/PDApainter.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/PDA_types.dm
  code/game/objects/objs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/chameleon.dm
  icons/obj/pda.dmi
  icons/obj/pda_alt.dmi
  icons/obj/pda_modern.dmi
  icons/obj/pda_rugged.dmi
  modular_citadel/code/game/objects/items/devices/PDA/PDA.dm
  modular_citadel/code/modules/reagents/reagent container/hypovial.dm
  modular_citadel/icons/obj/pda.dmi
  tgstation.dme
Labels: Feature, Refactor, Sprites

#157 Input Shortcuts
  code/controllers/subsystem/input.dm
Labels: Tweak

#162 Removes bad random events
  code/modules/events/aurora_caelus.dm
  code/modules/events/false_alarm.dm
Labels: Removal

#156 IC Word filtering
  code/controllers/configuration/configuration.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserassets/js/browserOutput.js
  code/modules/mob/living/say.dm
  config/in_character_filter.txt
Labels: Config Update, Feature

#163 Removes 18+ sprites
  code/_globalvars/lists/maintenance_loot.dm
  code/game/objects/items/storage/dakis.dm
  icons/mob/dogborg.dmi
  icons/mob/robots.dmi
  icons/mob/screen_cyborg.dmi
  icons/obj/daki.dmi
  icons/obj/plushes.dmi
  modular_citadel/icons/mob/citadel_refs/dogborg animations.dmi
  modular_citadel/icons/mob/citadel_refs/widerobot_vr.dmi
  modular_citadel/icons/mob/legacy robo transforms.dmi
  modular_citadel/icons/obj/genitals/breasts.dmi
  modular_citadel/icons/obj/genitals/breasts_onmob.dmi
  modular_citadel/icons/obj/genitals/dildo.dmi
  modular_citadel/icons/obj/genitals/effects.dmi
  modular_citadel/icons/obj/genitals/hud.dmi
  modular_citadel/icons/obj/genitals/onahole.dmi
  modular_citadel/icons/obj/genitals/ovipositor.dmi
  modular_citadel/icons/obj/genitals/penis.dmi
  modular_citadel/icons/obj/genitals/penis_onmob.dmi
  modular_citadel/icons/obj/genitals/taur_penis_onmob.dmi
  modular_citadel/icons/obj/genitals/testicles.dmi
  modular_citadel/icons/obj/genitals/testicles_onmob.dmi
  modular_citadel/icons/obj/genitals/vagina.dmi
  modular_citadel/icons/obj/genitals/vagina_onmob.dmi
  tgstation.dme
Labels: Removal, Sprites

#161 Ports Alffd's TOS System
  SQL/tos.sql
  code/_globalvars/configuration.dm
  code/controllers/configuration/configuration.dm
  code/modules/mob/dead/new_player/login.dm
  code/modules/mob/dead/new_player/new_player.dm
  config/tos.txt
  modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
  tgstation.dme
Labels: Administration, Config Update, FUCK, Feature, High Priority, SQL Change

#183 To infinity and beyond
  modular_citadel/code/game/objects/ids.dm
  modular_kepler/code/game/objects/ids.dm
  modular_kepler/code/game/objects/items/cards_ids.dm
  tgstation.dme
Labels: Tweak

#118 [READY] Species rework
  code/__HELPERS/_cit_helpers.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/datums/dna.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/masks/_masks.dm
  code/modules/clothing/suits/toggles.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/dead/new_player/sprite_accessories/hair_head.dm
  code/modules/mob/dead/new_player/sprite_accessories/tails.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/angel.dm
  code/modules/mob/living/carbon/human/species_types/felinid.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/jellypeople.dm
  code/modules/mob/living/carbon/human/species_types/mothmen.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/surgery/bodyparts/bodyparts.dm
  code/modules/surgery/bodyparts/helpers.dm
  modular_citadel/code/init.dm
  modular_citadel/code/modules/awaymissions/citadel_ghostrole_spawners.dm
  modular_citadel/code/modules/client/preferences_savefile.dm
  modular_citadel/code/modules/mob/cit_emotes.dm
  modular_citadel/code/modules/mob/dead/new_player/sprite_accessories.dm
  modular_citadel/code/modules/mob/living/carbon/human/species_types/ipc.dm
  modular_citadel/icons/mob/mam_ears.dmi
  modular_citadel/icons/mob/mam_markings.dmi
  modular_citadel/icons/mob/mam_snouts.dmi
  modular_citadel/icons/mob/mam_tails OLD.dmi
  modular_citadel/icons/mob/mam_tails.dmi
  modular_citadel/icons/mob/mam_taur.dmi
  modular_citadel/icons/mob/taur_canine.dmi
  modular_citadel/icons/mob/taur_hooved.dmi
  modular_citadel/icons/mob/taur_naga.dmi
  tgstation.dme
Labels: FUCK, Needs Review, Removal, Tweak

#184 Squish
  code/modules/mob/emote.dm
  sound/effects/slime_squish.ogg
Labels: Feature, Sound

#191 ID Card Spritse + PDA Painter Rework
  code/game/machinery/PDApainter.dm
  code/game/machinery/aug_manipulator.dm
  code/modules/clothing/outfits/ert.dm
  code/modules/jobs/job_types/cargo_service.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  icons/obj/pda.dmi
  modular_kepler/code/game/objects/items/cards_ids.dm
  modular_kepler/icons/obj/card.dmi
  modular_kepler/icons/obj/robotics.dmi
Labels: Feature, Fix, Sprites, Tweak

#210 Flavor text fix
  modular_kepler/code/modules/client/preferences.dm
  tgstation.dme
Labels: Fix

#195 Fixes undeleted SQL queries (Again)
  modular_citadel/code/modules/mentor/mentor_memo.dm
  modular_kepler/code/modules/mob/dead/new_player/tos_procs.dm
Labels: Fix

#197 Removes headset loud mode
  code/game/objects/items/devices/radio/headset.dm
Labels: Removal

#198 Makes new player panel bigger
  code/modules/mob/dead/new_player/new_player.dm
Labels: Fix

#199 Changes radio colors to paras
  code/modules/goonchat/browserassets/css/browserOutput.css
  interface/stylesheet.dm
Labels: Tweak

#200 Fixes some oversights in the PDA redesign
  code/game/objects/items/devices/PDA/PDA.dm
Labels: Fix

#196 Changes forum button to discord button
  code/controllers/configuration/entries/general.dm
  config/config.txt
  interface/interface.dm
  modular_kepler/interface/skin.dmf
  tgstation.dme
Labels: Config Update, Tweak

#256 End-Round Log Parsing
  code/__HELPERS/_logging.dm
  code/game/world.dm
  config/config.txt
  modular_kepler/code/controllers/configuration/entries/general.dm
  tgstation.dme
Labels: Administration, Blame Affected, Config Update, Feature, Tools

#297 Changes announcements/consoles.
  code/__HELPERS/priority_announce.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/computer/communications.dm
Labels: Tweak

#313 Adds kitty ears as a loadout option
  modular_citadel/code/modules/client/loadout/head.dm
Labels: Feature

#312 Adds jumpskirts for most jobs
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/vending/wardrobes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/code/modules/client/loadout/_engineering.dm
  modular_citadel/code/modules/client/loadout/_medical.dm
  modular_citadel/code/modules/client/loadout/_science.dm
  modular_citadel/code/modules/client/loadout/_security.dm
  modular_citadel/code/modules/client/loadout/_service.dm
  modular_citadel/code/modules/clothing/under/under.dm
  tgstation.dme
Labels: Feature, Sprites

#322 Increases Upload Limit
  code/modules/client/client_procs.dm
Labels: Tweak

#326 Omega job fix
  code/modules/jobs/map_changes/map_changes.dm
Labels: Fix

#331 Fixes PDA cart menus
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/PDA/cart.dm
Labels: Fix

#332 Fixes emotes
  code/datums/emotes.dm
  code/modules/mob/emote.dm
Labels: Fix
